### ISSUE TITLE
Raw value type is extended too

### ISSUE THREAD

**Issue by thomas-fossati** [deeglaze/draft-deeglaze-amd-sev-snp-corim-profile#10]
S3.1.2:

> _"The only extensions are to $$flags-map-extensions."_

but `$raw-value-type-choice` is also extended.

**Comment by deeglaze** [comment]
I've removed the extensions. I'd like this environment and measurement labeling to not need a profile. If we assign some flags-map-extensions ranges to AMD to assign for their technologies, then I might consider using flags again. But we don't have an IANA registry yet.
