### ISSUE TITLE
Use `tag` for the profile URI

### ISSUE THREAD

**Issue by thomas-fossati** [deeglaze/draft-deeglaze-amd-sev-snp-corim-profile#9]
I suggest using the `tag` scheme for the profile identifier. We started with `http` too, but then moved to `tag` to avoid the URL being de-referenced. E.g.: `tag:amd.com,2024:please-permalink-me`

An alternative is to use `urn` which, in case you plan to move the document to RFC, would (one day) give you the fancy and compact `urn:ietf:rfc:rfcXYZ`. The problem with this is that until the document gets ratified you can't know what the value is ;-)

So, in general, `tag` looks safer and more usable than the alternatives.

**Comment by deeglaze** [comment]
Removed the profile entirely since there are no extensions.
